# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: tests/IgalfastARM

on:
  push:
    branches: [ "RavenDB-15744-v5.4-test" ]

env:
  DOTNET_VERSION: 7.0.203

jobs:
  release:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore

    - name: Test - Release
      run: dotnet test --configuration Release --no-restore
      env: # Or as an environment variable
        RAVEN_LICENSE: ${{ secrets.RAVEN_LICENSE }}
        RAVEN_MAX_RUNNING_TESTS: 1
      working-directory: ./test/IgalFastTests
